# Databricks App Configuration
# This file configures your Streamlit app for Databricks Apps

command: ["streamlit", "run", "app.py", "--server.port", "8000", "--server.address", "0.0.0.0"]

# Optional: Specify environment variables
env:
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"

