# Databricks App Configuration
# AI Calculator with natural language interface

command: ["streamlit", "run", "app.py", "--server.port", "8000", "--server.address", "0.0.0.0"]

# Environment variables
# ⚠️ TEMPORARY: Token hardcoded for hackathon demo
# TODO: Fix secret reference syntax after demo
env:
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"
  
  # Genie Space IDs - Multi-Agent Architecture
  # NOTE: All agents currently point to the same Genie space "Hackathon- SPIFF Analyzer"
  # This maintains the multi-agent design while using one backend space
  # Using WORKING space: 01f0c4ae99271d64835d414b8d43ddfb
  
  # Sales Performance Agent
  - name: GENIE_SALES_SPACE_ID
    value: "01f0c4ae99271d64835d414b8d43ddfb"
  
  # Analytics & Winners Agent
  - name: GENIE_ANALYTICS_SPACE_ID
    value: "01f0c4ae99271d64835d414b8d43ddfb"
  
  # Market Intelligence Agent
  - name: GENIE_MARKET_SPACE_ID
    value: "01f0c4ae99271d64835d414b8d43ddfb"
  
  # Voice Activations Agent
  - name: GENIE_VOICE_ACTIVATIONS_SPACE_ID
    value: "01f0c4ae99271d64835d414b8d43ddfb"
  
  # Primary Genie Space ID (for backward compatibility)
  - name: GENIE_SPACE_ID
    value: "01f0c4ae99271d64835d414b8d43ddfb"
  
  # Databricks Authentication (for Genie access)
  # ⚠️ TEMPORARY: Hardcoded for hackathon demo only!
  - name: DATABRICKS_HOST
    value: "https://dbc-4a93b454-f17b.cloud.databricks.com"
  - name: DATABRICKS_TOKEN
    value: "dapi5e40d9eb65d1af6c91866e0a35c4"  # ⚠️ TEMP: PAT token for hackathon
  
  # SQL Warehouse ID (for executing queries)
  - name: SQL_WAREHOUSE_ID
    value: "0962fa4cf0922125"  # Same warehouse connected to all Genie spaces

